# CURSO INTENSIVO DE NUMPY

## INSTALACIÓN

Se instala con conda install numpy

## INTRODUCCIÓN E IMPORTACIÓN

Es un paquete de computación eficiente muy enfocado al álgebra lineal.

Muy rápido porque usa muchas librerías de C.

El resto de paquetes de ML están basados en él.

Dos estructuras básicas vectores (array de una dimensión) y matrices (array de 2 dimensiones).

Como término que unifica ambos usaremos array.

In [1]:
import numpy as np

**¿Por qué Numpy?**

Ahora que ya conocemos las estructuras de datos de Python vemos que no tiene realmente ninguna realmente orientada a trabajar con cálculos de manera masiva.

Están más orientadas a almacenar y recuperar información, pero no a procesarla en grandes cantidades y de forma eficiente.

Por otro lado casi todos los métodos de análisis y de machine learning se basan en el concepto de vector.

Lo más parecido que tiene Python a un vector podría ser una lista. Pero esta carece de lo que se llaman "operaciones vectorizadas", es decir, aplicar el mismo cálculo a todos los componentes del vector, y que es clave en data science.

In [2]:
# Por ejemplo si creamos una lista y la multiplicamos por dos
# No conseguimos el efecto que seguramente estábamos esperando
lista = [1,2,3]
lista * 2

[1, 2, 3, 1, 2, 3]

In [3]:
# Necesitaríamos usar list comprehension (o un for) para hacerlo
[elemento * 2 for elemento in lista]

[2, 4, 6]

In [12]:
# Sin embargo si la pasamos a un vector de Numpy sí
lista_vec = np.array([1,2,3])
lista_vec * 2

array([2, 4, 6])

A nivel de estructura de datos Numpy utiliza el array multidimensional (array de n dimensiones)

In [4]:
v = np.array([1,2,3])
type(v)

numpy.ndarray

A nivel de tipo de dato es importante ver cómo lo define: con el tipo de dato (por ejemplo entero) más el número de bits que usa (16, 32, 64, etc.).

Es importante porque en Pandas veremos que usa la misma notación.

In [14]:
v.dtype

dtype('int64')

### Nota Codex: `dtype`, bits y memoria

`dtype` significa **data type**, es decir, el tipo de dato que NumPy guarda dentro del array.

Por ejemplo, si ves:

```python
dtype('int64')
```

significa que cada entero usa 64 bits, es decir, 8 bytes.

Esto importa mucho en data science porque un array puede tener millones de elementos. Cambiar de `int64` a `int32` puede reducir la memoria a la mitad, siempre que los valores quepan en `int32`.

Que no nos confunda que Numpy sea una librería numérica. También puede haber arrays no numéricos.

Pero eso sí, **todos los componentes del array tienen que ser del mismo tipo** (que será una de las cosas que nos llevará a Pandas).

In [5]:
# Codex solution à analiser
# Comparación de memoria entre int32 e int64.
a = np.array([1, 2, 3], dtype=np.int32)
b = np.array([1, 2, 3], dtype=np.int64)

print('a:', a.dtype, a.nbytes, 'bytes')
print('b:', b.dtype, b.nbytes, 'bytes')

a: int32 12 bytes
b: int64 24 bytes


In [6]:
v = np.array(['a','b','c'])
type(v)

numpy.ndarray

### Verificación Codex: enteros de tamaño fijo

A diferencia del `int` normal de Python, los enteros de NumPy tienen tamaño fijo. Eso permite eficiencia, pero también puede producir **overflow** si el resultado no cabe en el tipo.

Para ver el rango de un tipo entero:

```python
np.iinfo(np.int32)
np.iinfo(np.int64)
```

In [7]:
#Si ponemos de diferentes tipos vemos que los convierte para que sean del mismo tipo
v = np.array(['a',2,'c'])
v

array(['a', '2', 'c'], dtype='<U21')

### Nota Codex: NumPy busca un tipo común

Un array de NumPy intenta guardar todos sus elementos con el mismo `dtype`.

Por eso, si mezclas texto y números:

```python
np.array(['a', 2, 'c'])
```

NumPy convierte el `2` en texto. Esto es muy importante: un array mezclado puede dejar de ser numérico y perder la capacidad de hacer operaciones matemáticas normales.

## COMO CREAR UN ARRAY

### A PARTIR DE UNA LISTA

In [8]:
#Crear un vector a partir una lista
v = np.array([1,2,3])
v

array([1, 2, 3])

In [9]:
#Crear una matriz a partir de una lista de listas
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

### A PARTIR DE UN RANGO

In [10]:
#Crear un vector a partir de un rango
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [12]:
#Crear un vector interpolando entre dos números
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

### Nota Codex: `arange()` vs `linspace()`

Las dos funciones crean secuencias, pero responden a preguntas distintas.

`np.arange(inicio, fin, paso)`:

- controlas el salto entre valores;
- el final normalmente no se incluye.

`np.linspace(inicio, fin, cantidad)`:

- controlas cuántos valores quieres;
- por defecto incluye el inicio y el final.

Regla práctica:

- si te importa el **paso**, usa `arange()`;
- si te importa la **cantidad exacta de puntos**, usa `linspace()`.

### CREAR UN ARRAY PREDEFINIDO

In [13]:
#Crear un array de ceros (el parámetro es una tupla con filas, columnas)
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
#Crear una matriz de identidad
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### CREAR UN ARRAY ALEATORIO

Con los aletorios de Python que hemos visto solamente podíamos extraer uno de cada vez.

Teniendo que hacer list comprehension para obtener toda una lista.

In [15]:
#Esto nos devuelve solo un valor
import random as rd
rd.randint(1,10)

5

In [16]:
#Si quierámos por ejemplo 10
[rd.randint(1,10) for cada in range(10)]

[4, 8, 1, 2, 10, 4, 7, 6, 4, 5]

Sin embargo vamos a ver cómo con Numpy generamos directamente vectores (que podrán ser variables) que es normalmente lo que queremos.

In [17]:
#Aleatorios de 0-1 con distribución uniforme
np.random.rand(5,10)

array([[0.96080893, 0.40268051, 0.40044534, 0.28331723, 0.24047381,
        0.20122401, 0.95123653, 0.66690197, 0.0991745 , 0.41462628],
       [0.28955379, 0.00608219, 0.2382224 , 0.73979255, 0.39797995,
        0.39770642, 0.93283679, 0.07152418, 0.33820645, 0.54108005],
       [0.12098975, 0.07227544, 0.19063816, 0.01292982, 0.99864366,
        0.56856585, 0.67954846, 0.75294243, 0.84758057, 0.27914307],
       [0.32424835, 0.45765004, 0.23439059, 0.57413302, 0.63994735,
        0.20262954, 0.7157281 , 0.08531547, 0.77020069, 0.34758538],
       [0.08361198, 0.23718808, 0.35206883, 0.57635385, 0.83505763,
        0.47718587, 0.16741013, 0.92778689, 0.4215797 , 0.97638164]])

In [18]:
#Aleatorios de distribución normal con media cero
np.random.randn(20)

array([ 0.188169  ,  2.24565586,  2.24329484, -0.15170875,  0.53582866,
        0.16634344, -0.08311047, -0.66090615, -2.10081908, -0.85494708,
        0.88140855,  0.85296837, -1.25356959, -1.34929907, -0.7118304 ,
       -0.7127507 ,  1.01946695,  0.94707915, -0.56216719, -1.16452959])

In [19]:
#Aleatorios entre dos enteros (inferior, superior, tamaño)
np.random.randint(1,11,20)

array([ 1,  4,  4,  1,  6,  8,  9,  4,  9, 10,  1,  7,  7,  8,  6, 10,  9,
        7,  4,  6], dtype=int32)

In [20]:
#También es muy útil establecer una semilla
np.random.seed(1234)

### Nota Codex: semilla y reproducibilidad

La semilla permite repetir los mismos números aleatorios. Esto es muy útil para aprender, depurar y comparar resultados.

En código moderno de NumPy, se recomienda usar un generador explícito:

```python
rng = np.random.default_rng(1234)
```

Las funciones antiguas como `np.random.rand()` siguen funcionando, pero `default_rng()` es mejor hábito para proyectos.

In [28]:
# Codex solution à analiser
# Alternativa moderna con default_rng().
rng = np.random.default_rng(1234)

print("Array de 5x10 con números aleatorios entre 0 y 1:\n")
print(rng.random((5, 10))) # genera un array de 5x10 con números aleatorios entre 0 y 1
print("\n Array de 5 números aleatorios con distribución normal:")
print("\n" + str(rng.normal(size=5))) # genera un array de 5 números aleatorios con distribución normal
print("\n Array de 10 números aleatorios entre 1 y 10:")
print("\n" + str(rng.integers(1, 11, size=10))) # genera un array de 10 números aleatorios entre 1 y 10

Array de 5x10 con números aleatorios entre 0 y 1:

[[0.97669977 0.38019574 0.92324623 0.26169242 0.31909706 0.11809123
  0.24176629 0.31853393 0.96407925 0.2636498 ]
 [0.44100612 0.60987081 0.8636213  0.86375767 0.67488131 0.65987435
  0.7357577  0.22275366 0.17206618 0.87041497]
 [0.06013866 0.68368891 0.67123802 0.61101798 0.06013731 0.97776927
  0.43895163 0.53259502 0.00313229 0.25126711]
 [0.85849044 0.42529835 0.73581899 0.92204322 0.15347417 0.99225923
  0.18233178 0.9401129  0.08688306 0.46821072]
 [0.8289892  0.28105226 0.86909151 0.97641657 0.84171366 0.4488736
  0.37050843 0.48266944 0.09218155 0.22668311]]

 Array de 5 números aleatorios con distribución normal:

[ 0.51309021  1.43709192 -0.22180411  0.6488165  -0.31789119]

 Array de 10 números aleatorios entre 1 y 10:

[4 8 3 5 2 5 7 8 4 9]


## COMO TRANSFORMAR UN ARRAY

### CAMBIAR LA FORMA Y ORDENAR

In [ ]:
#Ver la forma de una array
v = np.array([1,2,3])
# Devuelve una tupla con el número de filas y columnas. En este caso es un vector, por lo que devuelve (3,) 
# lo pone con una coma para indicar que es un vector si pone solo (3) sería un escalar. Si fuese una matriz de 3x4 devolvería (3,4)
v.shape 

(3,)

In [ ]:
#Ver la forma de una array
v = np.array([[1,2,3],[4,5,6]])
print(v)
# Devuelve una tupla con el número de filas y columnas. En este caso es una matriz de 2x3, por lo que devuelve (2,3)
v.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [35]:
#Cambiar la forma de un array
v = np.arange(20)
print(v)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [31]:
v.shape

(20,)

In [ ]:
# en machine learning no se utiliza mucho en deep learning se utiliza mucho para cambiar la forma de los datos de entrada
v2= v.reshape(2,10) 
print(v2)
v2.shape

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


(2, 10)

### Nota Codex: condición para hacer `reshape()`

Para cambiar la forma de un array, el número total de elementos tiene que cuadrar.

Ejemplo:

```python
v = np.arange(20)
```

Tiene 20 elementos. Entonces puede pasar a:

```python
(2, 10)  # 20 elementos
(4, 5)   # 20 elementos
(5, 4)   # 20 elementos
```

Pero no puede pasar a `(3, 7)`, porque eso necesitaría 21 elementos.

In [38]:
# Codex solution à analiser
# Usar -1 permite que NumPy calcule automáticamente una dimensión.
v = np.arange(20)

print(v.reshape(4, -1))  # 4 filas, columnas calculadas automáticamente
print("\n")
print(v.reshape(-1, 5))  # filas calculadas automáticamente, 5 columnas

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [39]:
#Ordenar
v = np.random.rand(10)
print(v)

[0.19151945 0.62210877 0.43772774 0.78535858 0.77997581 0.27259261
 0.27646426 0.80187218 0.95813935 0.87593263]


In [40]:
v.sort()
v

array([0.19151945, 0.27259261, 0.27646426, 0.43772774, 0.62210877,
       0.77997581, 0.78535858, 0.80187218, 0.87593263, 0.95813935])

### Nota Codex: `sort()` modifica el array original

`v.sort()` ordena el array **in-place**, es decir, modifica directamente `v`.

Si quieres obtener una versión ordenada sin tocar el array original, usa:

```python
np.sort(v)
```

Esta diferencia es muy importante porque muchas funciones de Python/NumPy pueden modificar el objeto original.

In [41]:
# Codex solution à analiser
# Comparación entre v.sort() y np.sort(v).
v = np.array([3, 1, 2])
ordenado = np.sort(v)

print('original:', v)
print('ordenado:', ordenado)

original: [3 1 2]
ordenado: [1 2 3]


### ESTADÍSTICOS BÁSICOS SOBRE UN ARRAY

In [42]:
#Estadísticos
v = np.arange(20)
print(v.mean())
print(np.median(v))
print(np.std(v))
print(v.var())
print(v.max())
print(v.min())
print(np.corrcoef(v,v))

9.5
9.5
5.766281297335398
33.25
19
0
[[1. 1.]
 [1. 1.]]


### Nota Codex: estadísticos con `axis`

En el ejemplo se calculan estadísticos sobre un vector. En matrices, normalmente queremos calcular por filas o por columnas.

Recuerda:

- `axis=0`: resume por columnas;
- `axis=1`: resume por filas.

Esto aparece constantemente en data science.

In [44]:
# Codex solution à analiser
# Estadísticos por filas y columnas.
m = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print('media total:', m.mean())
print('media por columnas:', m.mean(axis=0))
print('media por filas:', m.mean(axis=1))

media total: 50.0
media por columnas: [40. 50. 60.]
media por filas: [20. 50. 80.]


In [ ]:
#Localizar los índices de los estadísticos
v = np.random.randint(1,11,10)
print(v)
print(v.argmax())
v[v.argmax()]
print(v.argmin()) # 3 porque es la primera posición del valor mínimo que es 1
v[v.argmin()] 

[ 7  4  8  1 10  1  4  3  4  2]
4
3


np.int32(1)

### Nota Codex: `argmax()` devuelve posición, no valor

`v.max()` devuelve el valor máximo.

`v.argmax()` devuelve la posición del valor máximo.

Por eso para recuperar el valor usando la posición escribimos:

```python
v[v.argmax()]
```

### CREAR COPIAS

In [47]:
v1 = np.arange(5)
print(v1)

[0 1 2 3 4]


In [48]:
v2 = v1
v2

array([0, 1, 2, 3, 4])

In [49]:
v2[:] = 5

In [50]:
v2

array([5, 5, 5, 5, 5])

In [ ]:
# v1 se modifica también porque v2 es una vista de v1, no una copia. Para crear una copia, se puede usar el método copy().
v1

array([5, 5, 5, 5, 5])

In [56]:
#Para que no modifique el original hay que decir explícitamente que quieres una copia
#Si no lo entenderá como un puntero al original (parar ahorrar memoria) y lo podrá modificar
v1 = np.arange(5)
print("v1 =", v1)
print("\n")
v2 = v1.copy() # aquí se hace una copia de v1 y se asigna a v2, por lo que v2 es independiente de v1
v2[:] = 5 # ahora cambio v2 a 5, pero v1 no se verá afectado
print("v1 =", v1)
print("\n")
print("v2 =", v2)

v1 = [0 1 2 3 4]


v1 = [0 1 2 3 4]


v2 = [5 5 5 5 5]


### Verificación Codex: copia y vista

Cuando haces:

```python
v2 = v1
```

no creas un array nuevo. Creas otro nombre que apunta al mismo array.

Cuando haces:

```python
v2 = v1.copy()
```

sí creas un array independiente.

Esta diferencia evita muchos errores cuando se preparan datos para análisis o machine learning.

In [ ]:
# Codex solution à analiser
# Slicing básico suele crear una vista, no una copia.
v1 = np.arange(6)
print('v1:', v1)
v2 = v1[1:4] # es una vista de v1 sin el primer y último elemento, !no una copia!

v2[0] = 99

print('v1:', v1)
print('v2:', v2)

v1: [0 1 2 3 4 5]
v1: [ 0 99  2  3  4  5]
v2: [99  2  3]


## COMO INDEXAR UN ARRAY

In [58]:
#Indexar vectores
v = np.arange(11) 
print(v)
print(v[2])
print(v[2:5])

[ 0  1  2  3  4  5  6  7  8  9 10]
2
[2 3 4]


In [60]:
#Indexar matrices
#Creamos la matriz
m = np.random.rand(3,4)
print(m)

[[0.45272981 0.53814784 0.7906221  0.46583634]
 [0.43533225 0.56947866 0.969259   0.04055615]
 [0.54811957 0.4625766  0.37647223 0.32791208]]


In [ ]:
#Indexar matrices
#Indexar celdas

#Opción 1: con dos corchetes, el primero para las filas y el segundo para las columnas
print(m[0][0])

#Opción 2: con un solo corchete pero filas y columnas separadas por comas, la recomendada
print(m[0,0])

0.4527298092633677
0.4527298092633677


In [62]:
#Indexar matrices
#Indexar filas o columnas

#Filas
print(m[0,:])

#Columnas
print(m[:,0])

[0.45272981 0.53814784 0.7906221  0.46583634]
[0.45272981 0.43533225 0.54811957]


In [63]:
#Indexar matrices
#Indexar parcialmente filas o columnas

#Filas
print(m[0,0:2])

#Columnas
print(m[0:1,0])

[0.45272981 0.53814784]
[0.45272981]


In [64]:
#Indexar mediante vectores booleanos
#Las condiciones generan vectores booleanos
v = np.random.rand(10)
print(v)
print(v < 0.5)

[0.81352893 0.64655232 0.04742648 0.99495757 0.68923564 0.92954594
 0.91811655 0.97530172 0.39700197 0.26262609]
[False False  True False False False False False  True  True]


In [65]:
#Indexar mediante vectores booleanos
#Usar una condición como índice filtrará directamente el vector
v = np.random.rand(10)
print(v)
v[v < 0.5]

[0.43015136 0.76453077 0.59973081 0.08094696 0.70454447 0.16401332
 0.03234935 0.32815036 0.47386    0.06808472]


array([0.43015136, 0.08094696, 0.16401332, 0.03234935, 0.32815036,
       0.47386   , 0.06808472])

### Nota Codex: combinar filtros booleanos

Para una sola condición, esto funciona:

```python
v[v < 0.5]
```

Para varias condiciones, usamos `&`, `|` y paréntesis:

```python
v[(v > 0.2) & (v < 0.8)]
```

No usamos `and` porque NumPy compara elemento por elemento.

## EJERCICIOS DE CIERRE DE MODULO

### Nota Codex: cómo estudiar estos ejercicios

Para sacar más provecho, en cada ejercicio intenta responder tres preguntas:

1. ¿Qué forma tiene mi array? (`shape`)
2. ¿Estoy modificando el original o creando una copia?
3. ¿Puedo hacerlo vectorizado, sin bucles?

Estas tres preguntas son una buena rutina mental para trabajar con NumPy.

In [66]:
# Codex solution à analiser
# Filtrar valores entre 0.2 y 0.8.
v = np.random.rand(10)
print(v)

filtrado = v[(v > 0.2) & (v < 0.8)]
print(filtrado)

[0.3827107  0.11855414 0.89632852 0.76430853 0.37540494 0.02581418
 0.90653093 0.78641778 0.61931523 0.21158894]
[0.3827107  0.76430853 0.37540494 0.78641778 0.61931523 0.21158894]


### Crear una matriz de tamaño 6x3 con valores aleatorios enteros entre 10 y 100 y obtener el valor máximo de cada fila

In [ ]:
import numpy as np

m = np.random.randint(10,101,(6,3))
print(m)

print("valores máximos por fila:", m.max(1)) # 1 axis=1 indica que queremos el máximo por fila, si fuese axis=0 sería por columna

[[32 66 94]
 [18 54 34]
 [25 82 12]
 [26 12 89]
 [77 56 67]
 [65 46 98]]
valores máximos por fila: [94 54 82 89 77 98]


### A partir de una lista de números, crea un array y ordénalo en orden ascendente

In [70]:
lista = [7, 2, 9, 1, 5, 3]

v = np.array(lista)
v.sort()
print(v)

[1 2 3 5 7 9]


### Genera un array de 15 valores aleatorios con distribución normal y calcula su media, desviación estándar y varianza

In [72]:
v = np.random.randn(15) # randn genera números aleatorios con distribución normal, con media 0 y desviación estándar 1
print(v.mean())
print(v.std())
print(v.var())

0.31183183150922694
1.1034636781301546
1.2176320889525292


### Genera un array de 20 números enteros entre 1 y 50 y filtra aquellos que sean menores a 25

In [75]:
v = np.random.randint(1,51,20) # randint genera números aleatorios enteros entre 1 y 50, con tamaño 20
print(v)
print(v[v < 25])

[43  8 18  5  4 25 47 31 48 21  6 20  9  9 15 18 36 39  9 42]
[ 8 18  5  4 21  6 20  9  9 15 18  9]


### Crea un array secuencial de 12 elementos e intenta cambiar su forma a una matriz de 3x4 y otra de 2x6

In [77]:
v = np.arange(12)
m1 = v.reshape(3,4)
m2 = v.reshape(2,6)

print(v)
print("\n")
print(m1)
print("\n")
print(m2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


### Construye una matriz identidad de tamaño 4x4 y extrae su primera fila y su primera columna

In [80]:
m = np.eye(4)
print("matriz identidad:")
print(m)
print("primera fila:", m[0,:])
print("primera columna:", m[:,0])

matriz identidad:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
primera fila: [1. 0. 0. 0.]
primera columna: [1. 0. 0. 0.]


### Genera un array de 8 elementos aleatorios entre 1 y 10 y muestra el valor y la posición del máximo elemento

In [82]:
v = np.random.randint(1,11,8)
print(v)
print("Valor máximo:", v[v.argmax()], "en la posición:", v.argmax())

[ 4  5  3  2 10  5  1  1]
Valor máximo: 10 en la posición: 4


### Crea dos arrays aleatorios del mismo tamaño y calcula su matriz de correlación

#### Rappel : coefficient et matrice de corrélation

Le coefficient de corrélation mesure la relation linéaire entre deux variables :

- proche de `1` : les deux variables augmentent ensemble ;
- proche de `-1` : quand une variable augmente, l'autre diminue ;
- proche de `0` : il n'y a pas de relation linéaire claire.

`np.corrcoef(a, b)` renvoie une matrice de corrélation :

```python
[[corr(a, a), corr(a, b)],
 [corr(b, a), corr(b, b)]]
```

On a toujours `1` sur la diagonale car une variable est parfaitement corrélée avec elle-même : `corr(a, a) = 1` et `corr(b, b) = 1`.

In [87]:

# On crée deux tableaux de 10 valeurs aléatoires.
a = np.random.rand(10)
b = np.random.rand(10)

print("a:", a)
print("\nb:", b)

# [0, 1] donne la corrélation entre a et b.
print("\ncoeficiente de correlación:", np.corrcoef(a,b)[0,1])

# La matrice complète contient aussi corr(a,a) et corr(b,b), qui valent toujours 1.
print("\ncoeficiente de correlación (matriz completa):\n", np.corrcoef(a,b))

a: [0.86066665 0.45112463 0.97978134 0.54205321 0.68360807 0.93754947
 0.54670337 0.1652039  0.48875868 0.70090498]

b: [0.42004453 0.17756138 0.78183723 0.54316449 0.78156607 0.59354457
 0.10917367 0.01069769 0.01322471 0.45195242]

coeficiente de correlación: 0.7675692413795777

coeficiente de correlación (matriz completa):
 [[1.         0.76756924]
 [0.76756924 1.        ]]


### Muestra los valores mayores de 0.7 en un array de 12 números aleatorios entre 0 y 1

In [93]:
v = np.random.rand(12)

print(v)
print("\nvalores mayores a 0.7:", v[v > 0.7])

[0.39824479 0.23956812 0.77379412 0.42542123 0.98569388 0.86180394
 0.71057439 0.07704796 0.23163649 0.42776319 0.20753729 0.75349503]

valores mayores a 0.7: [0.77379412 0.98569388 0.86180394 0.71057439 0.75349503]


###  A partir de un array creado con arange, genera una copia, modifica sus valores y muestra ambos para verificar que el original no ha cambiado

In [96]:
v1 = np.arange(6)
print("v1 antes de modificar v2:")
print(v1)

v2 = v1.copy()
print(v1)
print("\nv2 antes de modificar:")
print(v2)

v2[:] = 9

print("v1 después de modificar v2:")
print(v1)
print("\nv2 después de modificar:")
print(v2)

v1 antes de modificar v2:
[0 1 2 3 4 5]
[0 1 2 3 4 5]

v2 antes de modificar:
[0 1 2 3 4 5]
v1 después de modificar v2:
[0 1 2 3 4 5]

v2 después de modificar:
[9 9 9 9 9 9]


## Verificación Codex con documentación oficial

Las notas añadidas se apoyan en la documentación oficial de NumPy:

- `dtype` y tipos de datos: cada array tiene un tipo fijo;
- `np.random.default_rng()`: recomendado para aleatoriedad moderna;
- copias y vistas: slicing básico puede compartir memoria;
- broadcasting e indexación booleana: base de la vectorización en NumPy;
- `axis`: clave para resumir matrices por filas o columnas.

La idea no es memorizar todas las funciones, sino aprender a pensar en arrays: forma, tipo, operación vectorizada y memoria.

## REPASO Y A RECORDAR

* Numpy es la base del análisis de datos masivo y eficiente con Python
* Y la base de paquetes posteriores como Pandas
* Sobre todo hay que conocer su estructura base: el array multidimensional
* Podemos crear arrays a partir de listas, rangos, estructuras predefinidas, distribuciones aleatorias, etc
* Los indexamos con los mismos recursos que ya conocemos, poniendo énfasis en el tema de las copias

Como lectura complementaria (y voluntaria no necesaria) para consolidar y complementar lo que hemos aprendido te recomiendo el siguiente post:

https://medium.com/better-programming/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d

En el cual se refuerzan estos conceptos de una forma muy gráfica que puede ayudar a su consolidación.