# CURSO INTENSIVO DE INTRODUCCIÓN AL ÁLGEBRA LINEAL

In [2]:
# Importamos NumPy, la libreria base para trabajar con arrays, vectores y matrices en Python.
import numpy as np

## INTRODUCCIÓN AL ÁLGEBRA LINEAL

Como decíamos al principio muchos de los algoritmos de machine learning se construyen con operaciones avanzadas sobre estructuras de datos como vectores o matrices.

Realmente no es necesario un conocimiento profundo de álgebra para hacer machine learning. Pero si es interesante por lo menos tener una nociones de lo que está pasando por debajo.

Y de nuevo el paquete base para hacer todo esto es Numpy, que seguiremos utilizando durante esta explicación.

**Un poco de teoría: profundizando en la comprensión de las estructuras de datos**

Hasta ahora hemos trabajado con tres tipos fundamentales de estructuras:

**Escalares** : en la lección de Python los llamábamos "datos individuales". Son valores simples, como un número, y se pueden asociar geométricamente a un punto. Por eso, decimos que tienen dimensión 0.

**Vectores** : son secuencias de escalares ordenadas. Geométricamente, un vector se representa como una flecha en el espacio y vive en un espacio de dimensión n, según el número de componentes. Por ejemplo, un vector de tres elementos vive en R3. Estructuralmente, también se pueden ver como matrices unidimensionales, ya sea de forma vertical (m×1) o horizontal (1×m).

**Matrices**: son colecciones de vectores organizados en filas y columnas. Desde un punto de vista geométrico, dos vectores independientes en Rn pueden definir un plano. Por eso, una matriz puede representar objetos bidimensionales (2D), y su forma se denota como m×n, con mm filas y nn columnas.

Podemos extender esta idea a estructuras más complejas, como los arrays multidimensionales (o tensores), que representan hiperplanos en espacios de dimensión superior. Estos aparecen, por ejemplo, en ciencia de datos, imágenes, o redes neuronales, y permiten trabajar con información en más de dos dimensiones.


 #### Nota Codex - Leer las formas antes de calcular
 
 En algebra lineal, casi siempre conviene mirar primero la **forma** de los objetos: escalar, vector, matriz o tensor. En NumPy esa forma se consulta con .shape. Si entiendes la forma, puedes anticipar si una operacion es posible antes de ejecutarla.
CodeCell

In [ ]:
# Ejemplo Codex: comprobar dimensiones con .shape
escalar = np.array(7)
vector = np.array([1, 2, 3])
matriz = np.array([[1, 2, 3], [4, 5, 6]])
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print('escalar shape:', escalar.shape) # Un escalar no tiene dimensiones, por lo que su shape es una tupla vacía. es un punto en el espacio.
print('vector shape:', vector.shape) # Un vector tiene una dimensión, por lo que su shape es una tupla con un solo elemento. es una línea en el espacio.
print('matriz shape:', matriz.shape) # Una matriz tiene dos dimensiones, por lo que su shape es una tupla con dos elementos. (usado en Álgebra Lineal para representar sistemas de ecuaciones, transformaciones lineales, tablas, etc.)
print('tensor shape:', tensor.shape) # Un tensor tiene tres dimensiones, por lo que su shape es una tupla con tres elementos. (usado en Deep Learning para representar imágenes, videos, etc.)

escalar shape: ()
vector shape: (3,)
matriz shape: (2, 3)
tensor shape: (2, 2, 2)


In [5]:
# Ejemplo de escalar con NumPy: un solo numero, sin direccion ni varias componentes.
np.array(1)

array(1)

In [6]:
# Ejemplo de vector con NumPy: una lista ordenada de numeros.
# Este vector tiene 3 componentes, por eso podemos imaginarlo en R3.
np.array([1, 2, 3])

array([1, 2, 3])

In [7]:
# Ejemplo de matriz con NumPy: filas y columnas.
# Aqui tenemos 2 filas y 3 columnas, es decir, una matriz de forma 2x3.
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# Ejemplo de array multidimensional: una estructura con mas de dos ejes.
# Puede entenderse como varias matrices apiladas.
np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### OPERACIONES CON VECTORES

#### SUMAR VECTORES

La condición es que tienen que tener la misma longitud

#### Nota Codex - Sumar vectores no es juntar listas

Cuando sumamos vectores, no estamos concatenando elementos. Sumamos cada posicion con su posicion equivalente. Por eso [1, 2, 3] + [4, 5, 6] da [5, 7, 9], no [1, 2, 3, 4, 5, 6].


In [9]:
# Creamos dos vectores con la misma longitud.
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# NumPy suma componente a componente: [1+4, 2+5, 3+6].
v1 + v2

array([5, 7, 9])

#### RESTAR VECTORES

La condición es que tienen que tener la misma longitud

In [10]:
# La resta tambien se hace componente a componente: [1-4, 2-5, 3-6].
v1 - v2

array([-3, -3, -3])

#### MULTIPLICAR UN VECTOR POR UN ESCALAR

In [11]:
# Multiplicar por un escalar cambia la magnitud del vector.
# Cada componente se multiplica por 10.
v1 * 10

array([10, 20, 30])

#### MULTIPLICAR DOS VECTORES

La condición es que tienen que tener la misma longitud

El tipo de multiplicación más usado es el producto escalar o producto punto: multiplicar uno a uno los correspondientes y luego sumar los resultados.

#### Nota Codex - Intuicion del producto escalar
 
 El producto escalar resume en un solo numero cuanto se parecen dos vectores en direccion y magnitud. Si el resultado es grande y positivo, suelen apuntar en una direccion parecida. Si es cercano a cero, hay poca alineacion. Esta idea aparece mucho en recomendadores, busqueda semantica y modelos de machine learning.
CodeCell

In [12]:
# Ejemplo Codex: producto escalar manual vs NumPy
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

producto_manual = (1 * 4) + (2 * 5) + (3 * 6)
producto_numpy = np.dot(v1, v2)

print(producto_manual)
print(producto_numpy)

32
32


In [13]:
# Revisamos el primer vector antes de calcular el producto punto.
v1

array([1, 2, 3])

In [14]:
# Revisamos el segundo vector: debe tener la misma longitud que v1.
v2

array([4, 5, 6])

In [15]:
# Producto escalar con np.dot:
# 1*4 + 2*5 + 3*6 = 32.
print(np.dot(v1, v2))

32


In [ ]:
# El operador @ hace el mismo producto escalar entre dos vectores 1D.

# np.dot(v1, v2) y v1 @ v2 hacen lo mismo con dos vectores 1D.
# np.dot es mas explicito para aprender el concepto.
# @ es mas comodo cuando escribimos operaciones de algebra lineal.

print(v1 @ v2)

32


Caso donde puedes ver la aplicación de este concepto para la creación de un sistema de recomendación:
https://youtu.be/paw7_cZoN1Q

### OPERACIONES CON MATRICES

#### SUMAR MATRICES

La condición es que tienen que tener la misma forma

#### Nota Codex - Misma forma significa mismas coordenadas

Para sumar o restar matrices, cada posicion debe tener una posicion equivalente en la otra matriz. Por eso una matriz 2x3 se puede sumar con otra 2x3, pero no con una 3x2, aunque ambas tengan 6 numeros.


In [17]:
# Dos matrices con la misma forma: 2 filas y 3 columnas.
m1 = np.array([[3, -4, 6], [0, -8, 3]])
m2 = np.array([[-1, -9, 7], [4, 8, -7]])

# La suma de matrices se hace posicion por posicion.
m1 + m2

array([[  2, -13,  13],
       [  4,   0,  -4]])

In [20]:
# Visualizamos m1 para recordar sus valores.
m1

array([[ 3, -4,  6],
       [ 0, -8,  3]])

In [18]:
# Visualizamos m2: tiene la misma forma que m1.
m2

array([[-1, -9,  7],
       [ 4,  8, -7]])

In [19]:
# Repetimos la suma para reforzar la idea de operacion elemento a elemento.
m1 + m2

array([[  2, -13,  13],
       [  4,   0,  -4]])

#### RESTAR MATRICES

La condición es que tienen que tener la misma forma

In [21]:
# La resta de matrices tambien se hace posicion por posicion.
m1 - m2

array([[  4,   5,  -1],
       [ -4, -16,  10]])

#### MULTIPLICAR UNA MATRIZ POR UN ESCALAR

In [22]:
# Multiplicar una matriz por un escalar multiplica cada elemento por ese valor.
m1 * 10

array([[ 30, -40,  60],
       [  0, -80,  30]])

#### MULTIPLICAR DOS MATRICES

Usaremos la forma del producto punto.

La condición es que el número de columnas de la primera tiene que ser el mismo que el número de filas de la segunda.

Más formalmente es multiplicar una m x n por una n x k.

Por ejemplo multiplicar una 3x2 por una 2x4.

Es así porque lo que hace el producto punto es ir multiplicando cada fila de la primera por cada columna de la segunda.

El resultado será una nueva matriz de m x k, ej 3x4.

Donde el producto punto de fila1 de la primera por columna 1 de la segunda será el resultado de la fila1,columna1 de la tercera.

#### Nota Codex - Regla de oro para multiplicar matrices
 
 Para multiplicar A @ B, mira las formas: (m, n) @ (n, k) = (m, k). Las dimensiones del centro deben coincidir. Las dimensiones de fuera anuncian la forma del resultado.
CodeCell

In [23]:
# Ejemplo Codex: anticipar la forma antes de multiplicar
A = np.array([[1, 2, 3], [4, 5, 6]])      # forma 2x3
B = np.array([[1, 0], [0, 1], [1, 1]])    # forma 3x2

print('A:', A.shape)
print('B:', B.shape)
print('A @ B:', (A @ B).shape)
A @ B

A: (2, 3)
B: (3, 2)
A @ B: (2, 2)


array([[ 4,  5],
       [10, 11]])

In [24]:
# Recordamos que m1 tiene forma 2x3.
m1

array([[ 3, -4,  6],
       [ 0, -8,  3]])

In [25]:
# shape nos devuelve la forma de la matriz: (filas, columnas).
m1.shape

(2, 3)

In [26]:
# Volvemos a mirar m1 antes de multiplicarla por otra matriz.
m1

array([[ 3, -4,  6],
       [ 0, -8,  3]])

In [27]:
# Creamos una matriz 3x3.
# Esto permite calcular m1 @ m3 porque m1 es 2x3 y m3 es 3x3.
m3 = np.array([
    [8, 6, 2],
    [6, 3, 4],
    [2, -4, 6]
])
m3.shape

(3, 3)

In [28]:
# Resultado de (2x3) @ (3x3): la forma final sera 2x3.
m1 @ m3

array([[ 12, -18,  26],
       [-42, -36, -14]])

#### APLANAR UNA MATRIZ

Habrá ocasiones en machine learning que aunque tengamos que usar una matriz el formato en el que tenemos que pasarle esa matriz a la clase que la procesará es un array unidimensional.

Aplanar una matriz (flatten en inglés) significa eso, pasarla de arrays multidimensionales a un vector, simplemente concatenando todas sus filas en una sola.

Lo hacemos con el método flatten de Numpy.

#### Nota Codex - Flatten conserva los datos, cambia la forma

Aplanar no cambia los valores, solo cambia como estan organizados. Es util cuando un algoritmo espera una sola fila de caracteristicas en vez de una matriz. En imagenes, por ejemplo, una matriz de pixeles puede transformarse en un vector de entrada.


In [29]:
# Recordemos como es la matriz m3 antes de aplanarla.
m3

array([[ 8,  6,  2],
       [ 6,  3,  4],
       [ 2, -4,  6]])

In [30]:
# flatten convierte la matriz en un vector 1D recorriendo las filas de izquierda a derecha.
m3.flatten()

array([ 8,  6,  2,  6,  3,  4,  2, -4,  6])

### PARA QUÉ SIRVE TODO ESTO

Muchas de las operaciones en ML se pueden hacer mediante álgebra matricial.

Y de hecho hacerlas asi es más eficiente computacionalmente.

Por lo que los algoritmos ya las hacen asi aunque nosotros no seamos conscientes ni tengamos que hacer nada al respecto.

**Deep learning:**

Deep learing es un subcampo de machine learning basado en la evolució de un algoritmo concreto llamado resdes neuronales.

Es un campo a parte, que puede ser visto como una especialización de machiene learning, y que necesita su propio curso completo.

Pero que sepas que si decides especializarte en DL entonces sí tendrás que profundizar un poco más sobre álgebra lineal. De momento no es necesario.

#### Nota Codex - Por que NumPy es tan importante en ML

NumPy permite expresar calculos en forma vectorizada: en vez de escribir bucles elemento por elemento, escribimos operaciones sobre arrays completos. Esto suele ser mas claro y mucho mas rapido, porque NumPy delega el trabajo pesado a codigo optimizado.


## EJERCICIOS DE REPASO

#### Nota Codex - Como resolver los ejercicios

Antes de escribir el resultado, haz siempre tres preguntas: que forma tiene cada objeto, que operacion me piden, y que forma deberia tener la respuesta. Ese habito evita muchos errores de dimensiones.


### Suma v1 más v2 y resta v3

In [34]:
# Ejercicio: suma v1 y v2, y despues resta v3.
import numpy as np

v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([5, 4, 3, 2, 1])
v3 = np.array([1, 1, 1, 1, 1])

# Todas las operaciones son componente a componente.
v1 + v2 - v3

array([5, 5, 5, 5, 5])

### Multiplica m1 por un escalar (3) y luego suma m2

In [35]:
# Primero multiplicamos cada elemento de m1 por 3.
# Luego sumamos m2 posicion por posicion.
m1 = np.array([[1, 2, 3], [4, 5, 6]])
m2 = np.array([[6, 5, 4], [3, 2, 1]])

m1 * 3 + m2

array([[ 9, 11, 13],
       [15, 17, 19]])

### Calcula el producto escalar entre estos dos vectores y luego multiplicalo por un escalar (2)

In [ ]:
# Calculamos el producto escalar entre v1 y v2.
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

producto = np.dot(v1, v2) # o v1 @ v2
print(producto)

# Despues multiplicamos ese resultado por el escalar 2.
print(producto * 2)

32
64


### ¿Se pueden multiplicar estas matrices? Anticipa la forma que tendrá el resultado

In [37]:
# m1 tiene forma 2x3 y m2 tiene forma 3x2.
# Se pueden multiplicar porque las dimensiones internas coinciden: 3 y 3.
# El resultado tendra forma 2x2.
m1 = np.array([[1, 2, 3], [4, 5, 6]])
m2 = np.array([[7, 8], [9, 10], [11, 12]])

m1 @ m2

array([[ 58,  64],
       [139, 154]])

### Multiplica estas matrices y aplana el resultado

In [38]:
# m2 es la matriz identidad: al multiplicar por ella, m1 no cambia.
m1 = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
m2 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

producto = m1 @ m2

# Aplanamos el resultado para convertirlo en un vector 1D.
producto.flatten()

array([1, 2, 3, 0, 1, 4, 5, 6, 0])

In [39]:
# Ejemplo Codex: multiplicar por la identidad no cambia la matriz
A = np.array([[2, -1], [0, 3]])
I = np.eye(2)

print(A @ I)
print(I @ A)

[[ 2. -1.]
 [ 0.  3.]]
[[ 2. -1.]
 [ 0.  3.]]


#### Nota Codex - La matriz identidad
 
 La matriz identidad funciona como el numero 1 en la multiplicacion: si las dimensiones son compatibles, A @ I = A e I @ A = A. Por eso aparece mucho en algebra lineal, optimizacion y modelos estadisticos.
CodeCell

In [ ]:
# Celda libre para probar tus propios vectores y matrices.
# Ejemplo: cambia los valores y observa como cambian los resultados.


## CONCEPTOS IMPORTANTES DE ALGEBRA LINEAL NO VISTOS EN EL CURSO
 
 #### Nota Codex - Mapa de lo que conviene estudiar despues
 
 Este cuaderno cubre las bases practicas: escalares, vectores, matrices, producto punto, producto matricial y aplanamiento. Para avanzar hacia machine learning, estos son conceptos importantes que todavia conviene conocer.
MdCell

### 1. Norma de un vector

#### Nota Codex

La norma mide el tamano o longitud de un vector. En machine learning se usa para medir distancias, magnitudes de errores y regularizacion. La norma euclidea de [3, 4] es 5, igual que en el teorema de Pitagoras.


In [31]:
# Ejemplo Codex: norma de un vector
v = np.array([3, 4]) # 3^2 + 4^2 = 9 + 16 = 25, sqrt(25) = 5
np.linalg.norm(v)

np.float64(5.0)

### 2. Distancia entre vectores

#### Nota Codex

La distancia euclidea entre dos vectores se calcula restando los vectores y midiendo la norma del resultado. Sirve, por ejemplo, para comparar observaciones o encontrar vecinos parecidos.


In [32]:
# Ejemplo Codex: distancia entre dos puntos
p1 = np.array([1, 2])
p2 = np.array([4, 6])

np.linalg.norm(p2 - p1)

np.float64(5.0)

### 3. Transpuesta de una matriz

#### Nota Codex

La transpuesta intercambia filas por columnas. Si una matriz tiene forma 2x3, su transpuesta tiene forma 3x2. Se usa mucho para preparar multiplicaciones matriciales.


In [33]:
# Ejemplo Codex: transpuesta
A = np.array([[1, 2, 3], [4, 5, 6]])

print(A.shape)
print(A.T.shape)
A.T

(2, 3)
(3, 2)


array([[1, 4],
       [2, 5],
       [3, 6]])

### 4. Determinante

#### Nota Codex

El determinante es un numero asociado a una matriz cuadrada. Si el determinante es cero, la matriz no tiene inversa. Geometricamente, indica como una transformacion cambia areas o volumenes.


In [ ]:
# Ejemplo Codex: determinante de una matriz cuadrada
A = np.array([[1, 2], [3, 4]])
np.linalg.det(A)

### 5. Matriz inversa

#### Nota Codex

La inversa de una matriz cuadrada es parecida al inverso de un numero. Si A_inv es la inversa de A, entonces A @ A_inv produce la matriz identidad. No todas las matrices tienen inversa.


In [ ]:
# Ejemplo Codex: inversa de una matriz
A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)

print(A_inv)
print(A @ A_inv)

### 6. Sistemas de ecuaciones lineales

#### Nota Codex

Muchos problemas se escriben como A @ x = b: conocemos A y , y queremos encontrar x. En NumPy se resuelve con 
p.linalg.solve, que suele ser mejor que calcular la inversa manualmente.


In [ ]:
# Ejemplo Codex: resolver A @ x = b
A = np.array([[2, 1], [1, 3]])
b = np.array([8, 13])

x = np.linalg.solve(A, b)
x

### 7. Valores y vectores propios

#### Nota Codex

Un vector propio mantiene su direccion cuando una matriz lo transforma; solo cambia su escala. Los valores propios indican cuanto se estira o encoge. Son fundamentales en PCA, reduccion de dimensionalidad y analisis de estabilidad.


In [ ]:
# Ejemplo Codex: valores y vectores propios
A = np.array([[2, 0], [0, 3]])
valores, vectores = np.linalg.eig(A)

print('valores propios:', valores)
print('vectores propios:')
print(vectores)

### 8. Rango de una matriz

#### Nota Codex

El rango mide cuanta informacion independiente contiene una matriz. Si una fila o columna se puede construir combinando otras, no aporta una nueva dimension de informacion.


In [ ]:
# Ejemplo Codex: rango de una matriz
A = np.array([[1, 2], [2, 4]])
np.linalg.matrix_rank(A)

### 9. Broadcasting

#### Nota Codex

Broadcasting es la capacidad de NumPy para combinar arrays de formas distintas cuando son compatibles. Es muy util, pero tambien puede generar errores si no revisamos bien las dimensiones.


In [ ]:
# Ejemplo Codex: broadcasting
M = np.array([[1, 2, 3], [4, 5, 6]])
v = np.array([10, 20, 30])

# v se suma a cada fila de M.
M + v

### 10. Descomposiciones matriciales

#### Nota Codex

Las descomposiciones separan una matriz en piezas mas simples. PCA, compresion de imagenes, recomendadores y muchos modelos numericos usan ideas como SVD, QR o eigendescomposicion. No hace falta dominarlas al principio, pero conviene saber que existen.


In [ ]:
# Ejemplo Codex: SVD, una descomposicion muy usada
A = np.array([[1, 2], [3, 4], [5, 6]])
U, S, Vt = np.linalg.svd(A)

print('U:', U.shape)
print('S:', S.shape)
print('Vt:', Vt.shape)
print(S)

### Cierre

#### Nota Codex

La idea importante no es memorizar todas las funciones, sino desarrollar el reflejo de pensar en formas, dimensiones y operaciones compatibles. Ese reflejo es la base para entender NumPy, pandas, machine learning y deep learning con mucha mas tranquilidad.
