# INTENSIVOS DE NUMPY Y ÁLGEBRA: EJERCICIOS COMENTADOS

Estos ejercicios sirven para repasar NumPy y las primeras ideas de álgebra lineal: vectores, matrices, operaciones elemento a elemento, producto escalar, selección con condiciones y cambio de forma de arrays.

#### Nota Codex

La idea no es memorizar todas las funciones, sino aprender a reconocer la **forma** de los datos y elegir la operación correcta. Antes de cada ejercicio, piensa: ¿trabajo con una lista, un vector o una matriz? ?La operación se hace elemento a elemento o es una operación de álgebra lineal?


## Ejercicio 1: importar NumPy

### Ejercicio a analizar

Importa NumPy usando el alias habitual `np`.


In [36]:
# Solución Codex
# Importamos NumPy con el alias np, que es la convención más usada.
import numpy as np


#### Nota Codex

Usar `np` evita escribir `numpy` completo cada vez. Por ejemplo, escribimos `np.array()` en lugar de `numpy.array()`.


## Ejercicio 2: lista de Python y suma con comprensión de listas

### Ejercicio a analizar

Crea una lista de Python con los números del 1 al 10. Después suma 5 a cada uno de sus elementos.


In [37]:
# Solución Codex
# range(1, 11) genera los números desde 1 hasta 10.
lista = list(range(1, 11))

# En Python puro, una lista no se puede sumar directamente con 5.
# Por eso usamos una comprensión de listas.
lista_mas_5 = [cada + 5 for cada in lista]
lista_mas_5


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

#### Nota Codex

En Python puro, `lista + 5` no funciona porque `+` entre listas significa concatenar listas, no sumar un número a cada elemento. Para hacer una operación elemento a elemento, usamos una comprensión de listas o NumPy.


In [38]:
# Solución alternativa Codex: usando un bucle clásico
resultado = []
for cada in lista:
    resultado.append(cada + 5)

resultado


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

## Ejercicio 3: hacer lo mismo con NumPy

### Ejercicio a analizar

Haz lo mismo, pero ahora usando NumPy. Primero crea un vector a partir de `lista`.


In [39]:
# Solución Codex
# Convertimos la lista de Python en un array de NumPy.
vector = np.array(lista)

# NumPy sí permite sumar 5 directamente a todos los elementos.
vector + 5


array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

#### Nota Codex

Esta es una de las grandes ventajas de NumPy: permite operaciones vectorizadas. Es decir, podemos operar sobre todo el array sin escribir un bucle explícito.


## Ejercicio 4: crear un array con `np.arange`

### Ejercicio a analizar

Crea un array directamente desde un rango, desde 100 hasta 200, avanzando de 10 en 10.


In [40]:
# Solución Codex
# np.arange(inicio, fin_excluido, paso)
# Ponemos 201 para incluir el 200.
np.arange(100, 201, 10)


array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200])

#### Nota Codex

`np.arange` se parece a `range`: el límite final no está incluido. Por eso, si queremos llegar hasta 200, usamos 201 como límite superior.


## Ejercicio 5: crear valores interpolados con `np.linspace`

### Ejercicio a analizar

Crea un array de 20 elementos interpolados desde 100 hasta 200.


In [41]:
# Solución Codex
# np.linspace(inicio, fin, cantidad)
# A diferencia de arange, aquí indicamos cuántos valores queremos.
np.linspace(100, 200, 20)


array([100.        , 105.26315789, 110.52631579, 115.78947368,
       121.05263158, 126.31578947, 131.57894737, 136.84210526,
       142.10526316, 147.36842105, 152.63157895, 157.89473684,
       163.15789474, 168.42105263, 173.68421053, 178.94736842,
       184.21052632, 189.47368421, 194.73684211, 200.        ])

#### Nota Codex

Usa `np.arange` cuando te importa el paso. Usa `np.linspace` cuando te importa la cantidad exacta de puntos.


## Ejercicio 6: matriz de ceros

### Ejercicio a analizar

Crea una matriz de 4 filas y 6 columnas rellena con ceros.


In [42]:
# Solución Codex
# La forma se escribe como una tupla: (filas, columnas).
ceros = np.zeros((4, 6))
ceros


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### Nota Codex

Una matriz de forma `(4, 6)` tiene 4 filas y 6 columnas. En álgebra lineal se suele decir matriz `4x6`.


## Ejercicio 7: matriz identidad

### Ejercicio a analizar

Crea una matriz identidad de 4 filas y 4 columnas.


In [43]:
# Solución Codex
# np.eye es la opción que conviene privilegiar porque es más flexible que np.identity.
identidad = np.eye(4)
identidad


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Nota Codex

`np.identity(4)` también funciona, pero `np.eye()` es más flexible: permite matrices rectangulares y diagonales desplazadas. La matriz identidad actúa como el número `1` en una multiplicación matricial compatible.


In [44]:
# Solución alternativa Codex
np.identity(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Ejercicio 8: matriz aleatoria uniforme

### Ejercicio a analizar

Crea una matriz de 6 filas y 3 columnas rellena con números aleatorios entre 0 y 1.


In [45]:
# Solución Codex
# np.random.rand(filas, columnas) genera valores entre 0 y 1.
matriz_aleatoria = np.random.rand(6, 3)
matriz_aleatoria


array([[0.98297119, 0.30496071, 0.83141343],
       [0.75221871, 0.60258624, 0.37280223],
       [0.87349448, 0.4169763 , 0.98277549],
       [0.69494586, 0.66494351, 0.56232143],
       [0.53778762, 0.91107001, 0.4202086 ],
       [0.77175451, 0.33585698, 0.89424995]])

#### Nota Codex

Estos valores siguen una distribución uniforme: todos los números entre 0 y 1 tienen, aproximadamente, la misma probabilidad de aparecer.


## Ejercicio 9: vector con distribución normal

### Ejercicio a analizar

Crea un vector aleatorio de 100 elementos que tenga una distribución normal.


In [46]:
# Solución Codex
# randn genera valores de una normal estándar: media 0 y desviación típica 1.
normal = np.random.randn(100)
normal


array([-0.53246069,  0.79021124, -0.37246758, -1.46966598,  0.24742777,
        1.48566107, -0.65702877, -0.8536569 ,  1.09539916,  1.22358951,
       -0.75988597,  1.24890818, -0.68712528,  1.33616423,  0.5483432 ,
        0.94036018, -0.0699812 , -1.24648253,  0.95042663,  0.36652283,
        0.02204403,  0.15843344,  0.10451027,  0.01610043,  1.00425074,
       -0.27355273, -2.03077578,  1.46839047, -0.04425414,  0.36675354,
       -0.3823512 ,  0.1736326 , -0.12917106,  0.40522269, -0.87733542,
       -0.58501552, -0.63661379,  1.77630461, -0.61077058, -0.15739763,
        1.42539529, -1.61967394, -0.51953935, -0.11401834,  0.86436581,
       -0.64081117,  0.59575508,  1.69535934, -1.34449498, -0.98280745,
        1.74663703,  1.25591673, -1.14941138, -0.3490359 ,  1.0115606 ,
        0.9140348 , -0.57643869,  0.31250533,  0.62071089, -1.51988553,
        0.13180504,  0.79433076,  1.06412603,  1.18009437, -0.51673439,
        0.03698339,  1.27378508, -0.94829172, -0.59697289,  0.67

#### Nota Codex

Una distribución normal estándar suele tener muchos valores cerca de 0 y menos valores muy alejados. En estadística y machine learning aparece constantemente.


## Ejercicio 10: vector aleatorio de enteros

### Ejercicio a analizar

Crea un vector aleatorio de 100 elementos que vayan entre 1 y 100.


In [47]:
# Solución Codex
# randint(inicio, fin_excluido, cantidad)
# Usamos 101 para que el 100 pueda aparecer.
enteros = np.random.randint(1, 101, 100)
enteros


array([33, 94, 10, 31, 18, 31, 86, 40, 83, 89, 80, 68, 70, 81, 24, 32,  6,
       97, 51, 11, 69, 91, 62, 90, 54, 60, 77, 19, 29, 60, 88, 13, 18, 89,
       96, 28, 19,  2, 42, 58,  3, 37, 15, 75, 45, 26, 35, 95, 75, 97, 15,
       55, 89, 28,  7, 58, 82, 45, 66, 11, 11, 23, 68, 20, 61, 61, 24,  9,
       22, 61, 65, 60, 96, 82, 41, 28,  2, 94, 38, 48, 54, 15, 33, 93, 85,
       47, 12, 28, 11,  3, 17, 26, 69,  5, 92,  4, 90, 40, 30, 61],
      dtype=int32)

#### Nota Codex

En `np.random.randint`, el límite superior no está incluido. Por eso `np.random.randint(1, 101, 100)` genera enteros desde 1 hasta 100.


## Ejercicio 11: crear y ordenar un vector

### Ejercicio a analizar

Crea un vector llamado `vector`, como el anterior, pero ordénalo.


In [48]:
# Solución Codex
vector = np.random.randint(1, 101, 100)

# sort() ordena el array en el mismo objeto y devuelve None.
vector.sort()
vector


array([ 2,  3,  3,  3,  4,  5,  6,  6,  8,  8,  8, 10, 10, 11, 13, 13, 13,
       14, 14, 15, 16, 16, 17, 18, 18, 19, 19, 21, 21, 22, 25, 27, 27, 28,
       28, 28, 28, 29, 30, 30, 31, 31, 33, 36, 38, 39, 40, 43, 43, 43, 43,
       45, 45, 45, 47, 48, 48, 50, 56, 58, 59, 60, 62, 63, 65, 67, 68, 69,
       71, 73, 75, 75, 77, 77, 77, 78, 78, 78, 79, 81, 81, 83, 83, 87, 88,
       89, 90, 90, 91, 92, 92, 93, 94, 94, 95, 95, 95, 96, 97, 99],
      dtype=int32)

#### Nota Codex

Atención: `vector.sort()` modifica `vector` directamente, pero no devuelve el vector ordenado. Por eso `print(vector.sort())` imprime `None`. Si quieres una copia ordenada, usa `np.sort(vector)`.


In [49]:
# Solución alternativa Codex: crear una copia ordenada
vector_original = np.random.randint(1, 101, 100)
vector_ordenado = np.sort(vector_original)

print('Original:', vector_original)
print('Ordenado:', vector_ordenado)


Original: [ 17  98  39  11   7  49  43  21  28  13  32  51  91  90  31  38  53  73
  10  80  39  75  15   5  83   8  83  99  87  65  50  28  43  70  71   7
  58  91  40  71  34  18  25  40   2  76  31  84  81  92  81  77  78  56
  45  40  40  65  56  24  59  85  45  49  35  87  63  85  33   6  35   3
  99  47  21  44  80  99  85  18  60  60  16  29  81  94  36  68  45  24
  26  26  92  14 100   3  85  39  64  26]
Ordenado: [  2   3   3   5   6   7   7   8  10  11  13  14  15  16  17  18  18  21
  21  24  24  25  26  26  26  28  28  29  31  31  32  33  34  35  35  36
  38  39  39  39  40  40  40  40  43  43  44  45  45  45  47  49  49  50
  51  53  56  56  58  59  60  60  63  64  65  65  68  70  71  71  73  75
  76  77  78  80  80  81  81  81  83  83  84  85  85  85  85  87  87  90
  91  91  92  92  94  98  99  99  99 100]


## Ejercicio 12: estadísticos básicos sobre `vector`

### Ejercicio a analizar

Sobre `vector`, calcula la media, mediana, desviación típica, varianza, máximo y mínimo.


In [50]:
# Solución Codex
print('Media:', vector.mean())
print('Mediana:', np.median(vector))
print('Desviación típica:', vector.std())
print('Varianza:', vector.var())
print('Máximo:', vector.max())
print('Mínimo:', vector.min())


Media: 47.54
Mediana: 43.0
Desviación típica: 30.917768354135777
Varianza: 955.9083999999998
Máximo: 99
Mínimo: 2


#### Nota Codex

La media resume el centro promedio. La mediana es el valor central cuando los datos están ordenados. La desviación típica y la varianza miden dispersión: cuánto se alejan los datos del centro.


In [51]:
# Solución alternativa Codex: usando funciones de NumPy
print('Media:', np.mean(vector))
print('Mediana:', np.median(vector))
print('Desviación típica:', np.std(vector))
print('Varianza:', np.var(vector))
print('Máximo:', np.max(vector))
print('Mínimo:', np.min(vector))


Media: 47.54
Mediana: 43.0
Desviación típica: 30.917768354135777
Varianza: 955.9083999999998
Máximo: 99
Mínimo: 2


## Ejercicio 13: extraer posiciones concretas

### Ejercicio a analizar

Extrae de `vector` los elementos que están entre el sexto y el octavo, ambos incluidos.


In [52]:
# Solución Codex
# En Python los índices empiezan en 0.
# Sexto elemento -> índice 5. Octavo elemento -> índice 7.
# En slicing, el límite derecho no se incluye, por eso usamos 8.
vector[5:8]


array([5, 6, 6], dtype=int32)

#### Nota Codex

La regla de slicing es `[inicio:fin_excluido]`. Si quieres incluir el índice 7, debes escribir `8` como límite final.


## Ejercicio 14: extraer los números pares

### Ejercicio a analizar

Extrae de `vector` los elementos que son pares. Pista: puedes apoyarte en el operador módulo `%`.


In [53]:
# Solución Codex
# Un número es par si el resto de dividirlo entre 2 es 0.
pares = vector[vector % 2 == 0]
pares


array([ 2,  4,  6,  6,  8,  8,  8, 10, 10, 14, 14, 16, 16, 18, 18, 22, 28,
       28, 28, 28, 30, 30, 36, 38, 40, 48, 48, 50, 56, 58, 60, 62, 68, 78,
       78, 78, 88, 90, 90, 92, 92, 94, 94, 96], dtype=int32)

#### Nota Codex

Aqué usamos una máscara booleana: `vector % 2 == 0` produce una serie de `True` y `False`. NumPy conserva solo las posiciones donde la condición es `True`.


In [54]:
# Ejemplo Codex: ver la máscara booleana en pequeño
mini_vector = np.array([1, 2, 3, 4, 5, 6])
mascara = mini_vector % 2 == 0

print(mascara)
print(mini_vector[mascara])


[False  True False  True False  True]
[2 4 6]


## Ejercicio 15: sumar dos vectores aleatorios

### Ejercicio a analizar

Crea dos vectores de enteros llamados `v1` y `v2`, cada uno de 5 elementos aleatorios entre 1 y 10, y súmalos.


In [55]:
# Solución Codex
v1 = np.random.randint(1, 11, 5)
v2 = np.random.randint(1, 11, 5)

suma = v1 + v2

print('v1:', v1)
print('v2:', v2)
print('suma:', suma)


v1: [ 2  1  9  3 10]
v2: [5 9 8 4 4]
suma: [ 7 10 17  7 14]


#### Nota Codex

La suma de vectores se hace componente a componente. Como `v1` y `v2` tienen la misma longitud, NumPy puede sumarlos directamente.


## Ejercicio 16: producto escalar

### Ejercicio a analizar

Multiplícalos usando el producto escalar.


In [66]:
# Solución Codex
# np.dot es muy explícito para aprender el concepto de producto escalar.
producto_escalar = np.dot(v1, v2)
producto_escalar


np.int32(143)

#### Nota Codex

Con dos vectores 1D, `np.dot(v1, v2)` y `v1 @ v2` dan el mismo resultado. Para aprender, `np.dot` deja claro que estamos haciendo un producto escalar; para álgebra lineal más compacta, `@` es muy cómodo.


In [67]:
# Solución alternativa Codex
v1 @ v2


np.int32(143)

## Ejercicio 17: transformar un vector en matriz

### Ejercicio a analizar

Transforma el vector que creaste antes llamado `vector` en una matriz de `10 x 10` y llámala `matriz`.


In [58]:
# Solución Codex
# vector tiene 100 elementos, y 10 x 10 = 100.
# Por eso el reshape es compatible.
matriz = vector.reshape(10, 10)
matriz


array([[ 2,  3,  3,  3,  4,  5,  6,  6,  8,  8],
       [ 8, 10, 10, 11, 13, 13, 13, 14, 14, 15],
       [16, 16, 17, 18, 18, 19, 19, 21, 21, 22],
       [25, 27, 27, 28, 28, 28, 28, 29, 30, 30],
       [31, 31, 33, 36, 38, 39, 40, 43, 43, 43],
       [43, 45, 45, 45, 47, 48, 48, 50, 56, 58],
       [59, 60, 62, 63, 65, 67, 68, 69, 71, 73],
       [75, 75, 77, 77, 77, 78, 78, 78, 79, 81],
       [81, 83, 83, 87, 88, 89, 90, 90, 91, 92],
       [92, 93, 94, 94, 95, 95, 95, 96, 97, 99]], dtype=int32)

#### Nota Codex

`reshape` no cambia los datos, solo reorganiza su forma. La condición clave es que el número total de elementos debe coincidir: 100 elementos pueden convertirse en una matriz `10x10`.


In [59]:
# Solución alternativa Codex
np.reshape(vector, (10, 10))


array([[ 2,  3,  3,  3,  4,  5,  6,  6,  8,  8],
       [ 8, 10, 10, 11, 13, 13, 13, 14, 14, 15],
       [16, 16, 17, 18, 18, 19, 19, 21, 21, 22],
       [25, 27, 27, 28, 28, 28, 28, 29, 30, 30],
       [31, 31, 33, 36, 38, 39, 40, 43, 43, 43],
       [43, 45, 45, 45, 47, 48, 48, 50, 56, 58],
       [59, 60, 62, 63, 65, 67, 68, 69, 71, 73],
       [75, 75, 77, 77, 77, 78, 78, 78, 79, 81],
       [81, 83, 83, 87, 88, 89, 90, 90, 91, 92],
       [92, 93, 94, 94, 95, 95, 95, 96, 97, 99]], dtype=int32)

## Ejercicio 18: multiplicar una matriz por un escalar

### Ejercicio a analizar

Multiplica `matriz` por 8.


In [60]:
# Solución Codex
# Multiplicar por un escalar multiplica cada elemento de la matriz.
matriz * 8


array([[ 16,  24,  24,  24,  32,  40,  48,  48,  64,  64],
       [ 64,  80,  80,  88, 104, 104, 104, 112, 112, 120],
       [128, 128, 136, 144, 144, 152, 152, 168, 168, 176],
       [200, 216, 216, 224, 224, 224, 224, 232, 240, 240],
       [248, 248, 264, 288, 304, 312, 320, 344, 344, 344],
       [344, 360, 360, 360, 376, 384, 384, 400, 448, 464],
       [472, 480, 496, 504, 520, 536, 544, 552, 568, 584],
       [600, 600, 616, 616, 616, 624, 624, 624, 632, 648],
       [648, 664, 664, 696, 704, 712, 720, 720, 728, 736],
       [736, 744, 752, 752, 760, 760, 760, 768, 776, 792]], dtype=int32)

#### Nota Codex

Esta operación es elemento a elemento. No es una multiplicación matricial entre dos matrices; simplemente cada valor se multiplica por `8`.


# EJEMPLOS ADICIONALES CODEX

Esta sección reúne complementos útiles para evitar errores frecuentes cuando trabajas con NumPy y álgebra lineal.


## Complemento 1: fijar la semilla aleatoria

#### Nota Codex

Cuando usamos números aleatorios, cada ejecución puede dar resultados diferentes. Para practicar o corregir ejercicios, a veces conviene fijar una semilla con `np.random.seed()` y así obtener siempre los mismos valores.


In [61]:
# Ejemplo Codex
np.random.seed(42)
np.random.randint(1, 11, 5)


array([7, 4, 8, 5, 7], dtype=int32)

## Complemento 2: diferencia entre `sort()` y `np.sort()`

#### Nota Codex

`array.sort()` ordena el array original y devuelve `None`. `np.sort(array)` devuelve una copia ordenada y conserva el array original sin modificar.


In [62]:
# Ejemplo Codex
datos = np.array([4, 1, 3, 2])
copia_ordenada = np.sort(datos)

print('datos original:', datos)
print('copia ordenada:', copia_ordenada)

datos.sort()
print('datos después de sort():', datos)


datos original: [4 1 3 2]
copia ordenada: [1 2 3 4]
datos después de sort(): [1 2 3 4]


## Complemento 3: revisar formas antes de operar

#### Nota Codex

Muchos errores de NumPy vienen de dimensiones incompatibles. Antes de sumar, multiplicar o hacer `reshape`, revisa `.shape`.


In [63]:
# Ejemplo Codex
A = np.ones((2, 3))
B = np.ones((3, 2))

print('A:', A.shape)
print('B:', B.shape)
print('A @ B:', (A @ B).shape)


A: (2, 3)
B: (3, 2)
A @ B: (2, 2)


## Complemento 4: broadcasting básico

#### Nota Codex

Broadcasting permite combinar arrays de formas distintas cuando NumPy puede extender una dimensión automáticamente. Es potente, pero hay que usarlo con cuidado.


In [64]:
# Ejemplo Codex
M = np.array([[1, 2, 3], [4, 5, 6]])
v = np.array([10, 20, 30])

# v se suma a cada fila de M.
M + v


array([[11, 22, 33],
       [14, 25, 36]])

## Complemento 5: producto matricial frente a producto elemento a elemento

#### Nota Codex

`A * B` multiplica elemento a elemento. `A @ B` realiza producto matricial. Son operaciones diferentes y pueden dar resultados muy distintos.


In [65]:
# Ejemplo Codex
A = np.array([[1, 2], [3, 4]])
B = np.array([[10, 20], [30, 40]])

print('Elemento a elemento:')
print(A * B)

print('Producto matricial:')
print(A @ B)


Elemento a elemento:
[[ 10  40]
 [ 90 160]]
Producto matricial:
[[ 70 100]
 [150 220]]


## Cierre didáctico

#### Nota Codex

Para avanzar con NumPy, intenta siempre explicar tu código en voz alta: qué forma tiene cada objeto, qué operación haces y qué forma esperas obtener. Si puedes anticipar eso, ya estás pensando como alguien que domina las bases del álgebra lineal aplicada a datos.
